var content=`
time – tiempo – tempo – 時間 (時 shí time) (間 jiān interval)
person – persona – persona – 人 (人 rén person)
year – año – anno – 年 (年 nián year)
way – camino – modo – 方式 (方 fāng method/direction) (式 shì style/form)
day – día – giorno – 天 (天 tiān day/sky)
thing – cosa – cosa – 事情 (事 shì matter/affair) (情 qíng situation)
man – hombre – uomo – 男人 (男 nán male) (人 rén person)
world – mundo – mondo – 世界 (世 shì world/generation) (界 jiè boundary)
life – vida – vita – 生活 (生 shēng life/birth) (活 huó live)
hand – mano – mano – 手 (手 shǒu hand)
part – parte – parte – 部分 (部 bù part/section) (分 fēn portion/divide)
child – niño – bambino – 孩子 (孩 hái child) (子 zi child/son)
eye – ojo – occhio – 眼睛 (眼 yǎn eye) (睛 jīng eyeball)
woman – mujer – donna – 女人 (女 nǚ woman/female) (人 rén person)
place – lugar – luogo – 地方 (地 dì earth/place) (方 fāng direction/area)
work – trabajo – lavoro – 工作 (工 gōng work) (作 zuò do/make)
week – semana – settimana – 週 (週 zhōu week)
case – caso – caso – 案例 (案 àn case) (例 lì example)
point – punto – punto – 點 (點 diǎn point/dot)
government – gobierno – governo – 政府 (政 zhèng government/politics) (府 fǔ office)
company – empresa – azienda – 公司 (公 gōng public) (司 sī company)
number – número – numero – 數字 (數 shù number) (字 zì character)
group – grupo – gruppo – 群體 (群 qún group) (體 tǐ body)
problem – problema – problema – 問題 (問 wèn ask) (題 tí question/topic)
fact – hecho – fatto – 事實 (事 shì matter/fact) (實 shí real)
home – hogar – casa – 家 (家 jiā home/family)
water – agua – acqua – 水 (水 shuǐ water)
room – habitación – stanza – 房間 (房 fáng room/house) (間 jiān space/interval)
mother – madre – madre – 母親 (母 mǔ mother) (親 qīn parent/relative)
area – área – area – 區域 (區 qū area) (域 yù region)
money – dinero – denaro – 錢 (錢 qián money)
story – historia – storia – 故事 (故 gù old/past) (事 shì story/matter)
issue – asunto – questione – 問題 (問 wèn ask) (題 tí question/topic)
side – lado – lato – 側 (側 cè side)
school – escuela – scuola – 學校 (學 xué study) (校 xiào school)
state – estado – stato – 州 (州 zhōu state/province)
family – familia – famiglia – 家庭 (家 jiā family/home) (庭 tíng courtyard/family)
student – estudiante – studente – 學生 (學 xué study) (生 shēng student/life)
country – país – paese – 國家 (國 guó country) (家 jiā home/nation)
city – ciudad – città – 城市 (城 chéng city/wall) (市 shì market/city)
community – comunidad – comunità – 社區 (社 shè community/society) (區 qū area)
service – servicio – servizio – 服務 (服 fú serve) (務 wù duty)
friend – amigo – amico – 朋友 (朋 péng friend) (友 yǒu friend)
father – padre – padre – 父親 (父 fù father) (親 qīn parent)
power – poder – potere – 力量 (力 lì strength) (量 liàng quantity/force)
hour – hora – ora – 小時 (小 xiǎo small) (時 shí time/hour)
game – juego – gioco – 遊戲 (遊 yóu play) (戲 xì game/drama)
line – línea – linea – 線 (線 xiàn line)
end – fin – fine – 結束 (結 jié tie/finish) (束 shù bind/end)
member – miembro – membro – 成員 (成 chéng become) (員 yuán member)
law – ley – legge – 法律 (法 fǎ law) (律 lǜ regulation)
car – coche – auto – 車 (車 chē car/vehicle)
result – resultado – risultato – 結果 (結 jié result) (果 guǒ fruit/result)
research – investigación – ricerca – 研究 (研 yán study) (究 jiū investigate)
name – nombre – nome – 名字 (名 míng name) (字 zì character)
body – cuerpo – corpo – 身體 (身 shēn body) (體 tǐ body)
parent – padre/madre – genitore – 父母 (父 fù father) (母 mǔ mother)
face – cara – faccia – 臉 (臉 liǎn face)
others – otros – altri – 其他人 (其 qí other/that) (他 tā he/other) (人 rén person)
level – nivel – livello – 程度 (程 chéng degree) (度 dù extent)
office – oficina – ufficio – 辦公室 (辦 bàn manage) (公 gōng public) (室 shì room)
door – puerta – porta – 門 (門 mén door)
health – salud – salute – 健康 (健 jiàn healthy) (康 kāng well-being)
art – arte – arte – 藝術 (藝 yì art/skill) (術 shù technique)
war – guerra – guerra – 戰爭 (戰 zhàn war) (爭 zhēng struggle)
history – historia – storia – 歷史 (歷 lì history) (史 shǐ history)
party – fiesta/partido – festa/partito – 派對/政黨 (派 pài group/faction) (對 duì pair/party) / (政 zhèng politics) (黨 dǎng party)
change – cambio – cambiamento – 變化 (變 biàn change) (化 huà transform)
morning – mañana – mattina – 早上 (早 zǎo early/morning) (上 shàng above/up)
reason – razón – ragione – 原因 (原 yuán cause/origin) (因 yīn reason)
girl – niña – ragazza – 女孩 (女 nǚ female) (孩 hái child)
guy – chico – ragazzo – 男孩 (男 nán male) (孩 hái child)
moment – momento – momento – 時刻 (時 shí time) (刻 kè moment)
air – aire – aria – 空氣 (空 kōng empty/air) (氣 qì energy/air)
teacher – maestro – insegnante – 老師 (老 lǎo old/respected) (師 shī teacher)
force – fuerza – forza – 力量 (力 lì strength) (量 liàng amount)
education – educación – educazione – 教育 (教 jiào teach) (育 yù educate)
foot – pie – piede – 腳 (腳 jiǎo foot)
boy – niño – ragazzo – 男孩 (男 nán male) (孩 hái child)
age – edad – età – 年齡 (年 nián year) (齡 líng age)
policy – política – politica – 政策 (政 zhèng politics) (策 cè policy/plan)
process – proceso – processo – 過程 (過 guò pass) (程 chéng process)
music – música – musica – 音樂 (音 yīn sound) (樂 yuè music/joy)
market – mercado – mercato – 市場 (市 shì market) (場 chǎng place)
sense – sentido – senso – 感覺 (感 gǎn feel) (覺 jué perceive)
nation – nación – nazione – 國家 (國 guó country) (家 jiā home)
plan – plan – piano – 計劃 (計 jì plan) (劃 huà map/plan)
college – colegio – università – 大學 (大 dà big) (學 xué study/school)
interest – interés – interesse – 興趣 (興 xìng interest) (趣 qù fun)
death – muerte – morte – 死亡 (死 sǐ death) (亡 wáng perish)
experience – experiencia – esperienza – 經驗 (經 jīng pass through) (驗 yàn experience)
effect – efecto – effetto – 效果 (效 xiào effect) (果 guǒ result)
use – uso – uso – 使用 (使 shǐ use) (用 yòng use)
class – clase – classe – 班級 (班 bān class/group) (級 jí level)
control – control – controllo – 控制 (控 kòng control) (制 zhì regulate)

be,ser/estar,essere,是 (是 shì to be)
have,tener,avere,有 (有 yǒu have)
do,hacer,fare,做 (做 zuò do)
say,decir,dire,說 (說 shuō say)
go,ir,andare,去 (去 qù go)
get,obtener,ottenere,得到 (得 dé get/obtain) (到 dào arrive)
make,hacer,fare,製作 (製 zhì manufacture) (作 zuò make)
know,saber/conocer,sapere,知道 (知 zhī know) (道 dào way/know)
think,pensar,pensare,想 (想 xiǎng think)
take,tomar,prendere,拿 (拿 ná take)
see,ver,vedere,看見 (看 kàn see/look) (見 jiàn see)
come,venir,venire,來 (來 lái come)
want,querer,volere,想要 (想 xiǎng want/think) (要 yào want)
look,mirar,guardare,看 (看 kàn look)
use,usar,usare,使用 (使 shǐ use) (用 yòng use)
find,encontrar,trovare,找到 (找 zhǎo look for) (到 dào find/arrive)
give,dar,dare,給 (給 gěi give)
tell,decir,dire,告訴 (告 gào tell/inform) (訴 sù report)
work,trabajar,lavorare,工作 (工 gōng work) (作 zuò do)
call,llamar,chiamare,打電話 (打 dǎ hit/make) (電 diàn electricity) (話 huà speech)
try,intentar,provare,嘗試 (嘗 cháng try/taste) (試 shì test/try)
ask,preguntar,chiedere,問 (問 wèn ask)
need,necesitar,avere bisogno,需要 (需 xū need) (要 yào want/need)
feel,sentir,sentire,感覺 (感 gǎn feel) (覺 jué sense)
become,convertirse,diventare,成為 (成 chéng become) (為 wéi be)
leave,salir/dejar,lasciare,離開 (離 lí leave) (開 kāi open/away)
put,poner,mettere,放 (放 fàng put/place)
mean,significar,significare,意思是 (意 yì meaning/idea) (思 sī think) (是 shì be)
keep,mantener,mantenere,保持 (保 bǎo keep/protect) (持 chí maintain)
let,dejar,lasciare,讓 (讓 ràng let/allow)
begin,empezar,iniziare,開始 (開 kāi open/begin) (始 shǐ start)
seem,parecer,sembrare,似乎 (似 sì seem) (乎 hū apparently)
help,ayudar,aiutare,幫助 (幫 bāng help) (助 zhù assist)
talk,hablar,parlare,談 (談 tán talk)
turn,girar,girare,轉 (轉 zhuǎn turn)
start,comenzar,iniziare,開始 (開 kāi open/start) (始 shǐ begin)
show,mostrar,mostrare,展示 (展 zhǎn display) (示 shì show)
hear,oír,sentire,聽見 (聽 tīng hear) (見 jiàn see)
play,jugar,giocare,玩 (玩 wán play)
run,correr,correre,跑 (跑 pǎo run)
move,mover,muovere,移動 (移 yí move) (動 dòng move)
like,gustar,piacere,喜歡 (喜 xǐ like) (歡 huān joy)
live,vivir,vivere,住 (住 zhù live)
believe,creer,credere,相信 (相 xiāng mutual) (信 xìn believe)
hold,sostener,tenere,握住 (握 wò grasp/hold) (住 zhù hold firmly)
bring,traer,portare,帶來 (帶 dài bring) (來 lái come)
happen,suceder,succedere,發生 (發 fā happen) (生 shēng arise)
must,deber,dovere,必須 (必 bì must) (須 xū must)
write,escribir,scrivere,寫 (寫 xiě write)
provide,proporcionar,fornire,提供 (提 tí provide) (供 gōng supply)
sit,sentarse,sedere,坐 (坐 zuò sit)
stand,estar de pie,stare in piedi,站 (站 zhàn stand)
lose,perder,perdere,失去 (失 shī lose) (去 qù go/away)
pay,pagar,pagare,支付 (支 zhī pay/support) (付 fù pay)
meet,encontrar,incontrare,見面 (見 jiàn see/meet) (面 miàn face)
include,incluir,includere,包括 (包 bāo include) (括 kuò enclose)
continue,continuar,continuare,繼續 (繼 jì continue) (續 xù continue)
set,colocar,impostare,設置 (設 shè set up) (置 zhì put/place)
learn,aprender,imparare,學習 (學 xué learn) (習 xí practice)
change,cambiar,cambiare,改變 (改 gǎi change) (變 biàn transform)
lead,liderar,condurre,領導 (領 lǐng lead) (導 dǎo guide)
understand,entender,capire,理解 (理 lǐ reason) (解 jiě explain/understand)
watch,mirar,guardare,觀看 (觀 guān watch/view) (看 kàn look)
follow,seguir,seguire,跟隨 (跟 gēn follow) (隨 suí follow/along)
stop,parar,fermare,停止 (停 tíng stop) (止 zhǐ stop)
create,crear,creare,創造 (創 chuàng create) (造 zào make)
speak,hablar,parlare,說話 (說 shuō speak) (話 huà words)
read,leer,leggere,讀 (讀 dú read)
allow,permitir,permettere,允許 (允 yǔn allow) (許 xǔ permit)
add,añadir,aggiungere,添加 (添 tiān add) (加 jiā add)
spend,gastar,spendere,花費 (花 huā spend) (費 fèi cost)
grow,crecer,crescere,成長 (成 chéng become) (長 zhǎng grow)
open,abrir,aprire,打開 (打 dǎ hit/open) (開 kāi open)
walk,caminar,camminare,走路 (走 zǒu walk) (路 lù road)
win,ganar,vincere,贏 (贏 yíng win)
offer,ofrecer,offrire,提供 (提 tí provide) (供 gōng offer)
remember,recordar,ricordare,記得 (記 jì remember) (得 dé recall)
love,amar,amare,愛 (愛 ài love)
consider,considerar,considerare,考慮 (考 kǎo consider) (慮 lǜ concern)
appear,aparecer,apparire,出現 (出 chū appear) (現 xiàn appear)
buy,comprar,comprare,買 (買 mǎi buy)
wait,esperar,aspettare,等待 (等 děng wait) (待 dài stay)
serve,servir,servire,服務 (服 fú serve) (務 wù duty/service)
die,morir,morire,死 (死 sǐ die)
send,enviar,inviare,發送 (發 fā send) (送 sòng send/deliver)
expect,esperar,aspettarsi,期望 (期 qī expect/period) (望 wàng hope)
build,construir,costruire,建造 (建 jiàn build) (造 zào construct)
stay,quedarse,stare,留下 (留 liú stay) (下 xià remain)
fall,caer,cadere,跌倒 (跌 diē fall) (倒 dǎo fall down)
cut,cortar,tagliare,剪 (剪 jiǎn cut)
reach,alcanzar,raggiungere,到達 (到 dào reach) (達 dá arrive)
kill,matar,uccidere,殺 (殺 shā kill)
remain,permanecer,rimanere,仍然 (仍 réng still) (然 rán so/yet)
suggest,sugerir,suggerire,建議 (建 jiàn build) (議 yì suggest/discuss)
raise,levantar,alzare,舉起 (舉 jǔ raise) (起 qǐ rise)
pass,pasar,passare,通過 (通 tōng pass through) (過 guò pass)
sell,vender,vendere,賣 (賣 mài sell)
require,requerir,richiedere,需要 (需 xū need) (要 yào require)
report,informar,riferire,報告 (報 bào report) (告 gào tell)
decide,decidir,decidere,決定 (決 jué decide) (定 dìng determine)


`;
